In [53]:
import pandas as pd
import numpy as np

In [54]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PatientID   5 non-null      int64
 1   Name        5 non-null      object
 2   Department  5 non-null      object
 3   Doctor      5 non-null      object
 4   BillAmount  5 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 240.0+ bytes

In [55]:
patient_df = pd.read_csv("Patient_Data.csv")
billing_df = pd.read_csv("Billing_Data.csv")

patient_df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

#### 1.	Load the patient dataset and show summary with info().

In [56]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

#### 2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [57]:
billing_columns = patient_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

billing_columns.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

#### 3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime']

In [58]:
patient_df = patient_df.drop(columns=['ReceptionistID', 'CheckInTime'])

patient_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

#### 4.	Use groupby to find total bill amount per department.

In [59]:
department_bill = patient_df.groupby('Department')['BillAmount'].sum()

print(department_bill)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

#### 5.	Remove duplicate patient records based on PatientID.

In [60]:
patient_df = patient_df.drop_duplicates(subset='PatientID')

patient_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

#### 6.	Fill missing BillAmount values with the mean bill amount.

In [61]:
patient_df['BillAmount'] = patient_df['BillAmount'].fillna(patient_df['BillAmount'].mean())

patient_df.head()

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

#### 7.	Merge the billing dataset with patient dataset on PatientID.

In [62]:
merged_df = pd.merge(patient_df, billing_df, on='PatientID')

merged_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

#### 8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [63]:
new_patients = pd.DataFrame({
    'PatientID':[1001,1002],
    'Name': ['Hari', 'Loki'],
    'Department':['Cardiology','Neurology'],
    'Doctor':['Dr.Hareesh','Dr.Lokesh'],
    'BillAmount':[4500,5200]
})

updated_patients = pd.concat([patient_df, new_patients], ignore_index=True)

updated_patients.tail()

   PatientID     Name   Department      Doctor   BillAmount
2        103  Charlie  Orthopedics     Dr. Lee  7500.000000
3        104    David   Cardiology   Dr. Smith  6200.000000
4        105      Eva  Dermatology    Dr. Rose  6233.333333
5       1001     Hari   Cardiology  Dr.Hareesh  4500.000000
6       1002     Loki    Neurology   Dr.Lokesh  5200.000000

#### 9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [64]:
billing_category = pd.DataFrame({
    'InsuranceCovered':[2000,1500,1800,2500,3000],
    'FinalAmount':[3000,4500,5200,6000,7000]
})

final_df = pd.concat([billing_df, billing_category], axis=1)

final_df.head()

   PatientID  InsuranceCovered  FinalAmount  InsuranceCovered  FinalAmount
0        101              2000         3000              2000         3000
1        102              1500         3500              1500         4500
2        103              2500         5000              1800         5200
3        104              3000         3200              2500         6000
4        105              1000         4000              3000         7000

In [65]:
merged_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000